{
 "title": "Cloud Run Golden Signals DEMO",
 "description": "Cloud Run Golden Signals - Traffic, Errors, Latency and Saturation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Traffic from Logging Agent API Request Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/request_count"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Latency chart based on Log based metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization using Compute CPU Utilization metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/container/cpu/utilizations"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_PERCENTILE_95",
      "preprocessor": "none",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Saturation Metrics - Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/container/memory/utilizations"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_PERCENTILE_95",
      "preprocessor": "none",
      "projectName": "codegarage-001-408013"
     }
    },
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/gce_bad_requests"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  }
 ]
}