{
 "title": "GCE Golden Signals",
 "description": "GCE Golden Signals - Traffic, Errors, Latency and Saturation",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "traffic_apache_default_metric",
   "type": "timeseries",
   "description": "Traffic from Logging Agent API Request Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "agent.googleapis.com/agent/request_count"
      ],
      "groupBys": [ "resource.label.instance_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  },
  {
   "title": "traffic_log_based_metrics",
   "type": "timeseries",
   "description": "Traffic - Good and Bad requests based on Log Based Metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/gce_good_requests"
      ],
      "groupBys": [ "resource.label.instance_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "codegarage-001-408013"
     }
    },
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/gce_bad_requests"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization using Compute CPU Utilization metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "compute.googleapis.com/instance/cpu/utilization"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Latency chart based on Log based metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "grafana-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/request_latency"
      ],
      "groupBys": [ "resource.label.instance_id" ],
      "perSeriesAligner": "ALIGN_PERCENTILE_95",
      "preprocessor": "none",
      "projectName": "codegarage-001-408013"
     }
    }
   ]
  }
 ]
}