{
 "title": "GKE App Metrics",
 "description": "After selecting your namespace and container you get a wealth of metrics like request rate, error rate, response times, pod count, cpu and memory usage. You can view cpu and memory usage in a variety of ways, compared to the limit, compared to the request, per pod, average per pod, etc.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "node",
    "label": "Node",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(istio_requests_total, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(istio_requests_total, pod)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(istio_requests_total, destination_workload)"
    }
   },
   { "name": "Filters" },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of Nodes",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/guest/cpu/load_15m",
      "perSeriesAligner": "ALIGN_COUNT",
      "preprocessor": "none",
      "projectName": "codegarage-377302",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "Number of Namespaces",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(istio_requests_total[1d])) by (destination_workload_namespace))"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "stat",
   "description": "Number of Apps",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(istio_requests_total[1d])) by (destination_workload))"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "description": "Number of Pods",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(istio_requests_total[1d])) by (pod))"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"}[1m])) by (destination_workload_namespace,destination_workload)",
     "legendFormat": "native | {{destination_workload}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\",response_code=~\"^[3-5][0-9]+\"}[1m])) by (destination_workload_namespace,destination_workload) / sum(irate(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"}[1m])) by (destination_workload_namespace,destination_workload)",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Availability",
   "type": "piechart",
   "description": "HTTP Status Code distribution",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"}[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "description": "HTTP Status Code distribution",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\",response_code=~\"^[3-5][0-9]+\"}) by (destination_workload,response_code)"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\",response_code=~\"^[2][0-9]+\"}) / sum(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"}) * 100"
    }
   ]
  },
  {
   "title": "Good Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\",response_code=~\"^[2][0-9]+\"})"
    }
   ]
  },
  {
   "title": "Bad Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\",response_code=~\"^[3-5][0-9]+\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(istio_requests_total{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Response time percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"}[30s])) by (app,kubernetes_namespace,le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"}[30s])) by (app,kubernetes_namespace,le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=~\"^$namespace$\", destination_workload=~\"^$app$\", pod=~\"^$pod$\"}[30s])) by (app,kubernetes_namespace,le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  },
  {
   "title": "CPU Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Traffic by App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.destination_workload_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [
       "metric.label.destination_workload_name"
      ],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/request_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "Usage relative to request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } }
 ]
}